# Front Routes File
front_homepage:
    path:     /
    defaults: { _controller: AppBundle:Front/Index:index }
    
request:
    path:       /request
    defaults:   { _controller: AppBundle:Front/Request:request } 
